image: node:10

cache:
  paths:
  - node_modules/

stages:
  - test
  services:
    - sqlite3
    - redis-server
  script:
   - yarn install
   - yarn test
  coverage:
    '/Statements.*?(\d+(?:\.\d+)?)%/' 
