
version: '3'

services:
  web:
    container_name: docker-datanomics-application
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SESSION_NAME=${SESSION_NAME}
      - SESSION_SECRET=${SESSION_SECRET}
